# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(deps/go): "
    groups:
      deps:
        patterns:
          - "*"
    open-pull-requests-limit: 15

  - package-ecosystem: npm
    # setup only for whole workspace to fix issues with package.lock,
    # SEE https://github.com/dependabot/dependabot-core/issues/4993#issuecomment-1739296001
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(deps/ui): "
    groups:
      prod-deps:
        dependency-type: production
      dev-deps:
        dependency-type: development
    open-pull-requests-limit: 15
    versioning-strategy: increase

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(deps/docker): "
    groups:
      deps:
        patterns:
          - "*"
    open-pull-requests-limit: 15

  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(deps/ci): "
    groups:
      deps:
        patterns:
          - "*"
    open-pull-requests-limit: 15
