name: Comment issue
description: Create comment on a issue

inputs:
  issue_number:
    required: true
    description: The issue number you want to comment
  content:
    required: true
    description: The content of comment

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      env:
        STDOUT: ${{ inputs.content }}
      with:
        script: |
          github.rest.issues.createComment({
              issue_number: ${{ inputs.issue_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.STDOUT
          })
