/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppNavigation: typeof import('./src/components/AppNavigation.vue')['default']
    AppNavigationDesktop: typeof import('./src/components/AppNavigationDesktop.vue')['default']
    AppNavigationMobile: typeof import('./src/components/AppNavigationMobile.vue')['default']
    AppNavigationSearch: typeof import('./src/components/AppNavigationSearch.vue')['default']
    FileUploader: typeof import('./src/components/FileUploader.vue')['default']
    ItemTextEditor: typeof import('./src/components/ItemTextEditor.vue')['default']
    LoadingLayer: typeof import('./src/components/LoadingLayer.vue')['default']
    LogTerminal: typeof import('./src/components/LogTerminal.vue')['default']
    PageEditor: typeof import('./src/components/PageEditor.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PreferenceArr: typeof import('./src/components/PreferenceArr.vue')['default']
    PreferenceGrp: typeof import('./src/components/PreferenceGrp.vue')['default']
    PreferenceItem: typeof import('./src/components/PreferenceItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteCreate: typeof import('./src/components/SiteCreate.vue')['default']
    SiteEditor: typeof import('./src/components/SiteEditor.vue')['default']
    SiteSwitcher: typeof import('./src/components/SiteSwitcher.vue')['default']
    UserEditor: typeof import('./src/components/UserEditor.vue')['default']
  }
}
