// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FileUploader: typeof import('./src/components/FileUploader.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ItemTextEditor: typeof import('./src/components/ItemTextEditor.vue')['default']
    LoadingLayer: typeof import('./src/components/LoadingLayer.vue')['default']
    LogTerminal: typeof import('./src/components/LogTerminal.vue')['default']
    PageEditor: typeof import('./src/components/PageEditor.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PreferenceArr: typeof import('./src/components/PreferenceArr.vue')['default']
    PreferenceGrp: typeof import('./src/components/PreferenceGrp.vue')['default']
    PreferenceItem: typeof import('./src/components/PreferenceItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteCreate: typeof import('./src/components/SiteCreate.vue')['default']
    SiteEditor: typeof import('./src/components/SiteEditor.vue')['default']
    SiteSwitcher: typeof import('./src/components/SiteSwitcher.vue')['default']
    Tab: typeof import('./src/components/Tab.vue')['default']
  }
}
