name: Build UI

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      ref:
        required: true
        type: string
      dry_run:
        required: true
        type: boolean
    secrets:
      NPM_TOKEN:
        required: false

permissions:
  contents: read
  id-token: write

jobs:
  build_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false

      - name: Use pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 10.33.2

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Validate package
        if: ${{ inputs.dry_run }}
        run: pnpm publish -F artalk --no-git-checks --dry-run

      - name: Publish
        if: ${{ !inputs.dry_run }}
        run: pnpm publish -F artalk --no-git-checks --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # GitHub Packages
      #
      # Setup .npmrc file to publish to GitHub Packages
      # - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      #   with:
      #     registry-url: 'https://npm.pkg.github.com'
      # # Publish to GitHub Packages
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
