name: Build App

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      dry_run:
        required: true
        type: boolean

jobs:
  build_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version }}
          # `go-releaser` will read the semver version from git tag name
          # `git-chglog` will diff the tag and generate changelog
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.2

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: pnpm

      - name: Setup git-chglog
        run: |
          curl -sL $(curl -s https://api.github.com/repos/git-chglog/git-chglog/releases/latest \
            | grep -oP '"https://.+linux_amd64.tar.gz"' | tr -d \") | tar -C /usr/local/bin -xz git-chglog
          git-chglog --version

      - name: Pre Build
        run: |-
          mkdir -p local

          # changelog
          git-chglog --config .github/chglog/config.yml ${{ inputs.version }} > local/release-notes.md

          # copy config file
          cp conf/artalk.example.yml artalk.yml

      - name: Print Relase Notes
        run: cat local/release-notes.md

      - name: Build and Release
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: v2.17.0
          args: release --clean --release-notes local/release-notes.md ${{ inputs.dry_run && '--skip=publish' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
