name: Docs CN Mirror Deploy

on:
  push:
    branches: ['master']
    paths: ['docs/**']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build Docs
        run: pnpm build:docs

      - name: Deploy
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          cos_bucket: ${{ secrets.DOCS_CN_COS_BUCKET }}
          cos_region: ${{ secrets.DOCS_CN_COS_REGION }}
          local_path: docs/docs/.vitepress/dist/
          remote_path: /
          clean: true
