name: Docs CN Mirror Deploy

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"

jobs:
  deploy:
    if: github.repository == 'ArtalkJS/Artalk'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build Docs
        run: pnpm docs:build

      - name: Deploy
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          cos_bucket: ${{ secrets.DOCS_CN_COS_BUCKET }}
          cos_region: ${{ secrets.DOCS_CN_COS_REGION }}
          local_path: .vitepress/dist/
          remote_path: /
          clean: true
