name: Test Frontend

on:
  push:
    paths:
      - 'ui/**'
  pull_request:
    paths:
      - 'ui/**'

jobs:
  test_ui:
    strategy:
      matrix:
        node: [18, 20]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./ui

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm --dir ./ui install --frozen-lockfile

      - name: Package Build Test
        run: pnpm build:all

      # TODO: Add unit test
      # - name: Unit test
      #   run: pnpm test
