name: Test Frontend

on:
  push:
    paths: [".github/workflows/test-frontend.yml", "ui/**", "package.json", "pnpm-lock.yaml"]
    branches-ignore: ["release/*", "nightly"]
    tags-ignore: ["v*"]
  pull_request:
    paths: [".github/workflows/test-frontend.yml", "ui/**", "package.json", "pnpm-lock.yaml"]
    branches-ignore: ["release/*", "nightly"]

permissions:
  contents: read

concurrency:
  group: test-frontend-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_ui:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            node: 22
            quality: true
          - os: ubuntu-24.04
            node: 24
            quality: false
          - os: windows-latest
            node: 22
            quality: false

    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    steps:
      - if: matrix.os == 'windows-latest'
        name: Set git to use LF (for Windows environment)
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 10.33.2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm # zizmor: ignore[cache-poisoning] test-only cache

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Package Build Test
        run: pnpm build:all

      - name: Unit Test
        run: pnpm test

      - name: Plugins Build Test
        if: ${{ matrix.quality }}
        run: pnpm build:plugins

      - name: Lint
        if: ${{ matrix.quality }}
        run: pnpm eslint ui && pnpm prettier --check ui

      # https://github.com/arethetypeswrong/arethetypeswrong.github.io
      - name: "arethetypeswrong test"
        if: ${{ matrix.quality }}
        run: pnpm -F artalk test:attw
