name: Test Docs

on:
  push:
    paths: ["docs/**"]
    branches-ignore: ["release/*", "nightly"]
    tags-ignore: ["v*"]
  pull_request:
    paths: ["docs/**"]
    branches-ignore: ["release/*", "nightly"]

permissions:
  contents: read

concurrency:
  group: test-docs-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Use pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 10.33.2

      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22.x
          cache: pnpm # zizmor: ignore[cache-poisoning] test-only cache

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Docs
        run: pnpm build:docs

      - name: Lint Docs
        run: pnpm eslint docs && pnpm prettier --check docs
