name: Test Frontend

on:
  push:
    paths: ["ui/**"]
    branches-ignore: ["release/*", "nightly"]
    tags-ignore: ["v*"]
  pull_request:
    paths: ["ui/**"]
    branches-ignore: ["release/*", "nightly"]

jobs:
  test_ui:
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: matrix.os == 'windows-latest'
        name: Set git to use LF (for Windows environment)
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.10.0

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Package Build Test
        run: pnpm build:all

      - name: Unit Test
        run: pnpm test

      - name: Plugins Build Test
        run: pnpm build:plugins

      - name: Lint
        run: pnpm eslint ui && pnpm prettier --check ui

      # https://github.com/arethetypeswrong/arethetypeswrong.github.io
      - name: "arethetypeswrong test"
        if: runner.os == 'ubuntu-latest'
        run: pnpm -F artalk test:attw || true
